name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新版本的 Ubuntu

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # 使用 GitHub Secrets 中的 Docker 用户名
          password: ${{ secrets.DOCKER_PASSWORD }}  # 使用 GitHub Secrets 中的 Docker 密码

      - name: Set up QEMU 
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # 设置 Docker Buildx

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6  # 构建并推送 Docker 镜像
        with:
          push: true  # 将镜像推送到 Docker Hub
          tags: ventsze/my-python-app:${{ github.ref_name }}  # 手动指定标签（使用 GitHub Release 的版本号）